{
 "title": "🙈 Trying to Copy The Dash/Plotly Dashboard at http://localhost:4567 - Provisioned",
 "time": { "from": "2023-10-31T05:24:34.422Z", "to": "2024-05-02T01:53:51.843Z" },
 "panels": [
  { "title": "From Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "🏷️ Number of Repositories With Standards Label",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", count FROM indicators WHERE indicator = 'REPOSITORIES_WITH_STANDARDS_LABEL' LIMIT 50 "
    }
   ]
  },
  {
   "title": "👴 Number of Repositories Archived by Automation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", count FROM indicators WHERE indicator = 'REPOSITORIES_ARCHIVED_BY_AUTOMATION' LIMIT 50 "
    }
   ]
  },
  {
   "title": "👀 Sentry Transactions Usage - Provisioned",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", count FROM indicators WHERE indicator = 'SENTRY_DAILY_TRANSACTION_USAGE' LIMIT 50 "
    }
   ]
  },
  { "title": "From CSV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "💥 GitHub Actions Usage Quota",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "Date", "type": "time" },
      { "name": "Product", "type": "string" },
      { "name": "Quantity", "type": "number" }
     ]
    }
   ]
  }
 ]
}